export const GET_ASSESSMENT_RESULT =
    "TugasAkhirSPBE/App/GET_ASSESSMENT_RESULT";
export const SET_ASSESSMENT_RESULT =
    "TugasAkhirSPBE/App/SET_ASSESSMENT_RESULT";
export const DOWNLOAD_FILE =
    "TugasAkhirSPBE/App/DOWNLOAD_FILE";
export const SUCCESS_DOWNLOAD_FILE =
    "TugasAkhirSPBE/App/SUCCESS_DOWNLOAD_FILE";