export const GET_ASSESSMENT_RESULT =
    "TugasAkhirSPBE/App/GET_ASSESSMENT_RESULT";
export const SET_ASSESSMENT_RESULT =
    "TugasAkhirSPBE/App/SET_ASSESSMENT_RESULT";
export const GET_ASSESSMENT_VALIDATION =
    "TugasAkhirSPBE/App/GET_ASSESSMENT_VALIDATION";
export const SET_ASSESSMENT_VALIDATION =
    "TugasAkhirSPBE/App/SET_ASSESSMENT_VALIDATION";
export const SEND_VALIDATION =
    "TugasAkhirSPBE/App/SEND_VALIDATION";
export const SUCCESS_SEND_VALIDATION =
    "TugasAkhirSPBE/App/SUCCESS_SEND_VALIDATION";