export const GET_ASSESSMENT_LIST =
    "TugasAkhirSPBE/App/GET_ASSESSMENT_LIST";
export const SET_ASSESSMENT_LIST =
    "TugasAkhirSPBE/App/SET_ASSESSMENT_LIST";
export const GET_ASSESSMENT_HISTORY =
    "TugasAkhirSPBE/App/GET_ASSESSMENT_HISTORY";
export const SET_ASSESSMENT_HISTORY =
    "TugasAkhirSPBE/App/SET_ASSESSMENT_HISTORY";
export const GET_INSTITUTION_LIST =
    "TugasAkhirSPBE/App/GET_INSTITUTION_LIST";
export const SET_INSTITUTION_LIST =
    "TugasAkhirSPBE/App/SET_INSTITUTION_LIST";