export const GET_INSTITUTION_DATA =
    "TugasAkhirSPBE/App/GET_INSTITUTION_DATA";
export const SET_INSTITUTION_DATA =
    "TugasAkhirSPBE/App/SET_INSTITUTION_DATA";
export const UPDATE_INSTITUTION_DATA =
    "TugasAkhirSPBE/App/UPDATE_INSTITUTION_DATA";
export const SUCCESS_UPDATE_INSTITUTION_DATA =
    "TugasAkhirSPBE/App/SUCCESS_UPDATE_INSTITUTION_DATA";
export const GET_INSTITUTION_LIST =
    "TugasAkhirSPBE/App/GET_INSTITUTION_LIST";
export const SET_INSTITUTION_LIST =
    "TugasAkhirSPBE/App/SET_INSTITUTION_LIST";