export const GET_INSTITUTION_LIST =
    "TugasAkhirSPBE/App/GET_INSTITUTION_LIST";
export const SET_INSTITUTION_LIST =
    "TugasAkhirSPBE/App/SET_INSTITUTION_LIST";
export const GET_EVALUATION_DATA =
    "TugasAkhirSPBE/App/GET_EVALUATION_DATA";
export const SET_EVALUATION_DATA =
    "TugasAkhirSPBE/App/SET_EVALUATION_DATA";
export const UPDATE_EVALUATION_DATA =
    "TugasAkhirSPBE/App/UPDATE_EVALUATION_DATA";
export const SUCCESS_UPDATE_EVALUATION_DATA =
    "TugasAkhirSPBE/App/SUCCESS_UPDATE_EVALUATION_DATA";