export const INSTITUTION_LIST = {
    "NAD_ACEH":
        [
            "Kabupaten Aceh Barat",
            "Kabupaten Aceh Barat Daya",
            "Kabupaten Aceh Besar",
            "Kabupaten Aceh Jaya",
            "Kabupaten Aceh Selatan",
            "Kabupaten Aceh Singkil",
            "Kabupaten Aceh Tamiang",
            "Kabupaten Aceh Tengah",
            "Kabupaten Aceh Tenggara",
            "Kabupaten Aceh Timur",
            "Kabupaten Aceh Utara",
            "Kabupaten Bener Meriah",
            "Kabupaten Bireuen",
            "Kabupaten Gayo Lues",
            "Kabupaten Nagan Raya",
            "Kabupaten Pidie",
            "Kabupaten Pidie Jaya",
            "Kabupaten Simeulue",
            "Kota Banda Aceh",
            "Kota Langsa",
            "Kota Lhokseumawe",
            "Kota Sabang",
            "Kota Subulussalam"
        ],
    "SUMATERA_UTARA":
        [
            "Kabupaten Asahan",
            "Kabupaten Batubara",
            "Kabupaten Dairi",
            "Kabupaten Deli Serdang",
            "Kabupaten Humbang Hasundutan",
            "Kabupaten Karo",
            "Kabupaten Labuhanbatu",
            "Kabupaten Labuhanbatu Selatan",
            "Kabupaten Labuhanbatu Utara",
            "Kabupaten Langkat",
            "Kabupaten Mandailing Natal",
            "Kabupaten Nias",
            "Kabupaten Nias Barat",
            "Kabupaten Nias Selatan",
            "Kabupaten Nias Utara",
            "Kabupaten Padang Lawas",
            "Kabupaten Padang Lawas Utara",
            "Kabupaten Pakpak Bharat",
            "Kabupaten Samosir",
            "Kabupaten Serdang Bedagai",
            "Kabupaten Simalungun",
            "Kabupaten Tapanuli Selatan",
            "Kabupaten Tapanuli Tengah",
            "Kabupaten Tapanuli Utara",
            "Kabupaten Toba Samosir",
            "Kota Binjai",
            "Kota Gunungsitoli",
            "Kota Medan",
            "Kota Padangsidempuan",
            "Kota Pematangsiantar",
            "Kota Sibolga",
            "Kota Tanjungbalai",
            "Kota Tebing Tinggi"
        ],
    "SUMATERA_BARAT":
        [
            "Kabupaten Agam",
            "Kabupaten Dharmasraya",
            "Kabupaten Kepulauan Mentawai",
            "Kabupaten Lima Puluh Kota",
            "Kabupaten Padang Pariaman",
            "Kabupaten Pasaman",
            "Kabupaten Pasaman Barat",
            "Kabupaten Pesisir Selatan",
            "Kabupaten Sijunjung",
            "Kabupaten Solok",
            "Kabupaten Solok Selatan",
            "Kabupaten Tanah Datar",
            "Kota Bukittinggi",
            "Kota Padang",
            "Kota Padangpanjang",
            "Kota Pariaman",
            "Kota Payakumbuh",
            "Kota Sawahlunto",
            "Kota Solok"
        ],
    "SUMATERA_SELATAN":
        [
            "Kabupaten Banyuasin",
            "Kabupaten Empat Lawang",
            "Kabupaten Lahat",
            "Kabupaten Muara Enim",
            "Kabupaten Musi Banyuasin",
            "Kabupaten Musi Rawas",
            "Kabupaten Musi Rawas Utara",
            "Kabupaten Ogan Ilir",
            "Kabupaten Ogan Komering Ilir",
            "Kabupaten Ogan Komering Ulu",
            "Kabupaten Ogan Komering Ulu Selatan",
            "Kabupaten Ogan Komering Ulu Timur",
            "Kabupaten Penukal Abab Lematang Ilir",
            "Kota Lubuklinggau",
            "Kota Pagar Alam",
            "Kota Palembang",
            "Kota Prabumulih"
        ],
    "RIAU":
        [
            "Kabupaten Bengkalis",
            "Kabupaten Indragiri Hilir",
            "Kabupaten Indragiri Hulu",
            "Kabupaten Kampar",
            "Kabupaten Kepulauan Meranti",
            "Kabupaten Kuantan Singingi",
            "Kabupaten Pelalawan",
            "Kabupaten Rokan Hilir",
            "Kabupaten Rokan Hulu",
            "Kabupaten Siak",
            "Kota Dumai",
            "Kota Pekanbaru"
        ],
    "KEPULAUAN_RIAU":
        [
            "Kabupaten Bintan",
            "Kabupaten Karimun",
            "Kabupaten Kepulauan Anambas",
            "Kabupaten Lingga",
            "Kabupaten Natuna",
            "Kota Batam",
            "Kota Tanjung Pinang"
        ],
    "JAMBI":
        [
            "Kabupaten Batanghari",
            "Kabupaten Bungo",
            "Kabupaten Kerinci",
            "Kabupaten Merangin",
            "Kabupaten Muaro Jambi",
            "Kabupaten Sarolangun",
            "Kabupaten Tanjung Jabung Barat",
            "Kabupaten Tanjung Jabung Timur",
            "Kabupaten Tebo",
            "Kota Jambi",
            "Kota Sungai Penuh"
        ],
    "BENGKULU":
        ["Kabupaten Bengkulu Selatan",
            "Kabupaten Bengkulu Tengah",
            "Kabupaten Bengkulu Utara",
            "Kabupaten Kaur",
            "Kabupaten Kepahiang",
            "Kabupaten Lebong",
            "Kabupaten Mukomuko",
            "Kabupaten Rejang Lebong",
            "Kabupaten Seluma",
            "Kota Bengkulu"
        ],
    "BANGKA_BELITUNG":
        [
            "Kabupaten Bangka",
            "Kabupaten Bangka Barat",
            "Kabupaten Bangka Selatan",
            "Kabupaten Bangka Tengah",
            "Kabupaten Belitung",
            "Kabupaten Belitung Timur",
            "Kota Pangkal Pinang"
        ],
    "LAMPUNG":
        [
            "Kabupaten Lampung Tengah",
            "Kabupaten Lampung Utara",
            "Kabupaten Lampung Selatan",
            "Kabupaten Lampung Barat",
            "Kabupaten Lampung Timur",
            "Kabupaten Mesuji",
            "Kabupaten Pesawaran",
            "Kabupaten Pesisir Barat",
            "Kabupaten Pringsewu",
            "Kabupaten Tulang Bawang",
            "Kabupaten Tulang Bawang Barat",
            "Kabupaten Tanggamus",
            "Kabupaten Way Kanan",
            "Kota Bandar Lampung",
            "Kota Metro"
        ],
    "BANTEN":
        [
            "Kabupaten Lebak",
            "Kabupaten Pandeglang",
            "Kabupaten Serang",
            "Kabupaten Tangerang",
            "Kota Cilegon",
            "Kota Serang",
            "Kota Tangerang",
            "Kota Tangerang Selatan"
        ],
    "JAWA_BARAT":
        [
            "Kabupaten Bandung",
            "Kabupaten Bandung Barat",
            "Kabupaten Bekasi",
            "Kabupaten Bogor",
            "Kabupaten Ciamis",
            "Kabupaten Cianjur",
            "Kabupaten Cirebon",
            "Kabupaten Garut",
            "Kabupaten Indramayu",
            "Kabupaten Karawang",
            "Kabupaten Kuningan",
            "Kabupaten Majalengka",
            "Kabupaten Pangandaran",
            "Kabupaten Purwakarta",
            "Kabupaten Subang",
            "Kabupaten Sukabumi",
            "Kabupaten Sumedang",
            "Kabupaten Tasikmalaya",
            "Kota Bandung",
            "Kota Banjar",
            "Kota Bekasi",
            "Kota Bogor",
            "Kota Cimahi",
            "Kota Cirebon",
            "Kota Depok",
            "Kota Sukabumi",
            "Kota Tasikmalaya"
        ],
    "JAWA_TENGAH":
        [
            "Kabupaten Banjarnegara",
            "Kabupaten Banyumas",
            "Kabupaten Batang",
            "Kabupaten Blora",
            "Kabupaten Boyolali",
            "Kabupaten Brebes",
            "Kabupaten Cilacap",
            "Kabupaten Demak",
            "Kabupaten Grobogan",
            "Kabupaten Jepara",
            "Kabupaten Karanganyar",
            "Kabupaten Kebumen",
            "Kabupaten Kendal",
            "Kabupaten Klaten",
            "Kabupaten Kudus",
            "Kabupaten Magelang",
            "Kabupaten Pati",
            "Kabupaten Pekalongan",
            "Kabupaten Pemalang",
            "Kabupaten Purbalingga",
            "Kabupaten Purworejo",
            "Kabupaten Rembang",
            "Kabupaten Semarang",
            "Kabupaten Sragen",
            "Kabupaten Sukoharjo",
            "Kabupaten Tegal",
            "Kabupaten Temanggung",
            "Kabupaten Wonogiri",
            "Kabupaten Wonosobo",
            "Kota Magelang",
            "Kota Pekalongan",
            "Kota Salatiga",
            "Kota Semarang",
            "Kota Surakarta",
            "Kota Tegal"
        ],
    "JAWA_TIMUR":
        [
            "Kabupaten Bangkalan",
            "Kabupaten Banyuwangi",
            "Kabupaten Blitar",
            "Kabupaten Bojonegoro",
            "Kabupaten Bondowoso",
            "Kabupaten Gresik",
            "Kabupaten Jember",
            "Kabupaten Jombang",
            "Kabupaten Kediri",
            "Kabupaten Lamongan",
            "Kabupaten Lumajang",
            "Kabupaten Madiun",
            "Kabupaten Magetan",
            "Kabupaten Malang",
            "Kabupaten Mojokerto",
            "Kabupaten Nganjuk",
            "Kabupaten Ngawi",
            "Kabupaten Pacitan",
            "Kabupaten Pamekasan",
            "Kabupaten Pasuruan",
            "Kabupaten Ponorogo",
            "Kabupaten Probolinggo",
            "Kabupaten Sampang",
            "Kabupaten Sidoarjo",
            "Kabupaten Situbondo",
            "Kabupaten Sumenep",
            "Kabupaten Trenggalek",
            "Kabupaten Tuban",
            "Kabupaten Tulungagung",
            "Kota Batu",
            "Kota Blitar",
            "Kota Kediri",
            "Kota Madiun",
            "Kota Malang",
            "Kota Mojokerto",
            "Kota Pasuruan",
            "Kota Probolinggo",
            "Kota Surabaya"
        ],
    "DKI_JAKARTA":
        [
            "Kota Administrasi Jakarta Barat",
            "Kota Administrasi Jakarta Pusat",
            "Kota Administrasi Jakarta Selatan",
            "Kota Administrasi Jakarta Timur",
            "Kota Administrasi Jakarta Utara",
            "Kabupaten Administrasi Kepulauan Seribu"
        ],
    "DAERAH_ISTIMEWA_YOGYAKARTA":
        [
            "Kabupaten Bantul",
            "Kabupaten Gunungkidul",
            "Kabupaten Kulon Progo",
            "Kabupaten Sleman",
            "Kota Yogyakarta"
        ],
    "BALI":
        [
            "Kabupaten Badung",
            "Kabupaten Bangli",
            "Kabupaten Buleleng",
            "Kabupaten Gianyar",
            "Kabupaten Jembrana",
            "Kabupaten Karangasem",
            "Kabupaten Klungkung",
            "Kabupaten Tabanan",
            "Kota Denpasar"
        ],
    "NUSA_TENGGARA_BARAT":
        [
            "Kabupaten Bima",
            "Kabupaten Dompu",
            "Kabupaten Lombok Barat",
            "Kabupaten Lombok Tengah",
            "Kabupaten Lombok Timur",
            "Kabupaten Lombok Utara",
            "Kabupaten Sumbawa",
            "Kabupaten Sumbawa Barat",
            "Kota Bima",
            "Kota Mataram"
        ],
    "NUSA_TENGGARA_TIMUR":
        [
            "Kabupaten Alor",
            "Kabupaten Belu",
            "Kabupaten Ende",
            "Kabupaten Flores Timur",
            "Kabupaten Kupang",
            "Kabupaten Lembata",
            "Kabupaten Malaka",
            "Kabupaten Manggarai",
            "Kabupaten Manggarai Barat",
            "Kabupaten Manggarai Timur",
            "Kabupaten Ngada",
            "Kabupaten Nagekeo",
            "Kabupaten Rote Ndao",
            "Kabupaten Sabu Raijua",
            "Kabupaten Sikka",
            "Kabupaten Sumba Barat",
            "Kabupaten Sumba Barat Daya",
            "Kabupaten Sumba Tengah",
            "Kabupaten Sumba Timur",
            "Kabupaten Timor Tengah Selatan",
            "Kabupaten Timor Tengah Utara",
            "Kota Kupang"
        ],
    "KALIMANTAN_BARAT":
        [
            "Kabupaten Bengkayang",
            "Kabupaten Kapuas Hulu",
            "Kabupaten Kayong Utara",
            "Kabupaten Ketapang",
            "Kabupaten Kubu Raya",
            "Kabupaten Landak",
            "Kabupaten Melawi",
            "Kabupaten Mempawah",
            "Kabupaten Sambas",
            "Kabupaten Sanggau",
            "Kabupaten Sekadau",
            "Kabupaten Sintang",
            "Kota Pontianak",
            "Kota Singkawang"
        ],
    "KALIMANTAN_SELATAN":
        [
            "Kabupaten Balangan",
            "Kabupaten Banjar",
            "Kabupaten Barito Kuala",
            "Kabupaten Hulu Sungai Selatan",
            "Kabupaten Hulu Sungai Tengah",
            "Kabupaten Hulu Sungai Utara",
            "Kabupaten Kotabaru",
            "Kabupaten Tabalong",
            "Kabupaten Tanah Bumbu",
            "Kabupaten Tanah Laut",
            "Kabupaten Tapin",
            "Kota Banjarbaru",
            "Kota Banjarmasin"
        ],
    "KALIMANTAN_TENGAH":
        [
            "Kabupaten Barito Selatan",
            "Kabupaten Barito Timur",
            "Kabupaten Barito Utara",
            "Kabupaten Gunung Mas",
            "Kabupaten Kapuas",
            "Kabupaten Katingan",
            "Kabupaten Kotawaringin Barat",
            "Kabupaten Kotawaringin Timur",
            "Kabupaten Lamandau",
            "Kabupaten Murung Raya",
            "Kabupaten Pulang Pisau",
            "Kabupaten Sukamara",
            "Kabupaten Seruyan",
            "Kota Palangka Raya"
        ],
    "KALIMANTAN_TIMUR":
        [
            "Kabupaten Berau",
            "Kabupaten Kutai Barat",
            "Kabupaten Kutai Kartanegara",
            "Kabupaten Kutai Timur",
            "Kabupaten Mahakam Ulu",
            "Kabupaten Paser",
            "Kabupaten Penajam Paser Utara",
            "Kota Balikpapan",
            "Kota Bontang",
            "Kota Samarinda"
        ],
    "KALIMANTAN_UTARA":
        [
            "Kabupaten Bulungan",
            "Kabupaten Malinau",
            "Kabupaten Nunukan",
            "Kabupaten Tana Tidung",
            "Kota Tarakan"
        ],
    "GORONTALO":
        [
            "Kabupaten Boalemo",
            "Kabupaten Bone Bolango",
            "Kabupaten Gorontalo",
            "Kabupaten Gorontalo Utara",
            "Kabupaten Pohuwato",
            "Kota Gorontalo"
        ],
    "SULAWESI_SELATAN":
        [
            "Kabupaten Bantaeng",
            "Kabupaten Barru",
            "Kabupaten Bone",
            "Kabupaten Bulukumba",
            "Kabupaten Enrekang",
            "Kabupaten Gowa",
            "Kabupaten Jeneponto",
            "Kabupaten Kepulauan Selayar",
            "Kabupaten Luwu",
            "Kabupaten Luwu Timur",
            "Kabupaten Luwu Utara",
            "Kabupaten Maros",
            "Kabupaten Pangkajene dan Kepulauan",
            "Kabupaten Pinrang",
            "Kabupaten Sidenreng Rappang",
            "Kabupaten Sinjai",
            "Kabupaten Soppeng",
            "Kabupaten Takalar",
            "Kabupaten Tana Toraja",
            "Kabupaten Toraja Utara",
            "Kabupaten Wajo",
            "Kota Makassar",
            "Kota Palopo",
            "Kota Parepare"
        ],
    "SULAWESI_TENGGARA":
        [
            "Kabupaten Bombana",
            "Kabupaten Buton",
            "Kabupaten Buton Selatan",
            "Kabupaten Buton Tengah",
            "Kabupaten Buton Utara",
            "Kabupaten Kolaka",
            "Kabupaten Kolaka Timur",
            "Kabupaten Kolaka Utara",
            "Kabupaten Konawe",
            "Kabupaten Konawe Kepulauan",
            "Kabupaten Konawe Selatan",
            "Kabupaten Konawe Utara",
            "Kabupaten Muna",
            "Kabupaten Muna Barat",
            "Kabupaten Wakatobi",
            "Kota Bau-Bau",
            "Kota Kendari"
        ],
    "SULAWESI_TENGAH":
        [
            "Kabupaten Banggai",
            "Kabupaten Banggai Kepulauan",
            "Kabupaten Banggai Laut",
            "Kabupaten Buol",
            "Kabupaten Donggala",
            "Kabupaten Morowali",
            "Kabupaten Morowali Utara",
            "Kabupaten Parigi Moutong",
            "Kabupaten Poso",
            "Kabupaten Sigi",
            "Kabupaten Tojo Una-Una",
            "Kabupaten Toli-Toli",
            "Kota Palu"
        ],
    "SULAWESI_UTARA":
        [
            "Kabupaten Bolaang Mongondow",
            "Kabupaten Bolaang Mongondow Selatan",
            "Kabupaten Bolaang Mongondow Timur",
            "Kabupaten Bolaang Mongondow Utara",
            "Kabupaten Kepulauan Sangihe",
            "Kabupaten Kepulauan Siau Tagulandang Biaro",
            "Kabupaten Kepulauan Talaud",
            "Kabupaten Minahasa",
            "Kabupaten Minahasa Selatan",
            "Kabupaten Minahasa Tenggara",
            "Kabupaten Minahasa Utara",
            "Kota Bitung",
            "Kota Kotamobagu",
            "Kota Manado",
            "Kota Tomohon"
        ],
    "SULAWESI_BARAT":
        [
            "Kabupaten Majene",
            "Kabupaten Mamasa",
            "Kabupaten Mamuju",
            "Kabupaten Mamuju Tengah",
            "Kabupaten Mamuju Utara",
            "Kabupaten Polewali Mandar",
            "Kota Mamuju"
        ],
    "MALUKU":
        [
            "Kabupaten Buru",
            "Kabupaten Buru Selatan",
            "Kabupaten Kepulauan Aru",
            "Kabupaten Maluku Barat Daya",
            "Kabupaten Maluku Tengah",
            "Kabupaten Maluku Tenggara",
            "Kabupaten Maluku Tenggara Barat",
            "Kabupaten Seram Bagian Barat",
            "Kabupaten Seram Bagian Timur",
            "Kota Ambon",
            "Kota Tual"
        ],
    "MALUKU_UTARA":
        [
            "Kabupaten Halmahera Barat",
            "Kabupaten Halmahera Tengah",
            "Kabupaten Halmahera Utara",
            "Kabupaten Halmahera Selatan",
            "Kabupaten Kepulauan Sula",
            "Kabupaten Halmahera Timur",
            "Kabupaten Pulau Morotai",
            "Kabupaten Pulau Taliabu",
            "Kota Ternate",
            "Kota Tidore Kepulauan"
        ],
    "PAPUA":
        [
            "Kabupaten Asmat",
            "Kabupaten Biak Numfor",
            "Kabupaten Boven Digoel",
            "Kabupaten Deiyai",
            "Kabupaten Dogiyai",
            "Kabupaten Intan Jaya",
            "Kabupaten Jayapura",
            "Kabupaten Jayawijaya",
            "Kabupaten Keerom",
            "Kabupaten Kepulauan Yapen",
            "Kabupaten Lanny Jaya",
            "Kabupaten Mamberamo Raya",
            "Kabupaten Mamberamo Tengah",
            "Kabupaten Mappi",
            "Kabupaten Merauke",
            "Kabupaten Mimika",
            "Kabupaten Nabire",
            "Kabupaten Nduga",
            "Kabupaten Paniai",
            "Kabupaten Pegunungan Bintang",
            "Kabupaten Puncak",
            "Kabupaten Puncak Jaya",
            "Kabupaten Sarmi",
            "Kabupaten Supiori",
            "Kabupaten Tolikara",
            "Kabupaten Waropen",
            "Kabupaten Yahukimo",
            "Kabupaten Yalimo",
            "Kota Jayapura"
        ],
    "PAPUA_BARAT":
        [
            "Kabupaten Fakfak",
            "Kabupaten Kaimana",
            "Kabupaten Manokwari",
            "Kabupaten Manokwari Selatan",
            "Kabupaten Maybrat",
            "Kabupaten Pegunungan Arfak",
            "Kabupaten Raja Ampat",
            "Kabupaten Sorong",
            "Kabupaten Sorong Selatan",
            "Kabupaten Tambrauw",
            "Kabupaten Teluk Bintuni",
            "Kabupaten Teluk Wondama"
        ],
    "INDUSTRI_TELEKOMUNIKASI_DAN_MEDIA":
        [
            "PT Telkom Indonesia (Persero) Tbk",
            "PT Danareksa (Persero)",
            "Perum Produksi Film Negara",
            "Perum Percetakan Uang Republik Indonesia"
        ],
    "INDUSTRI_ENERGI_MINYAK_DAN_GAS_BUMI":
        [
            "PT Pertamina (Persero)",
            "PT Perusahaan Listrik Negara (Persero)"
        ],
    "INDUSTRI_MINERAL_DAN_BATUBARA":
        [
            "PT Indonesia Asahan Aluminium (Persero)"
        ],
    "INDUSTRI_PERKEBUNAN_DAN_KEHUTANAN":
        [
            "PT Perkebunan Nusantara III (Persero)",
            "Perum Kehutanan Negara"
        ],
    "INDUSTRI_PANGAN":
        [
            "PT Pupuk Indonesia (Persero)",
            "PT Rajawali Nusantara Indonesia (Persero)",
            "Perum Badan Usaha Logistik"
        ],
    "INDUSTRI_KESEHATAN":
        [
            "PT Bio Farma (Persero)"
        ],
    "INDUSTRI_MANUFAKTUR_DAN_SURVEI":
        [
            "PT Biro Klasifikasi Indonesia (Persero)",
            "PT Krakatau Steel (Persero) Tbk",
            "PT Len Industri (Persero)",
            "PT Industri Kereta Api (Persero)"
        ],
    "JASA_KEUANGAN":
        [
            "PT Bank Mandiri (Persero) Tbk",
            "PT Bank Negara Indonesia (Persero) Tbk",
            "PT Bank Rakyat Indonesia (Persero) Tbk",
            "PT Bank Tabungan Negara (Persero) Tbk"
        ],
    "JASA_ASURANSI_DAN_DANA_PENSIUN":
        [
            "PT Asuransi Jiwasraya (Persero)",
            "PT Asuransi Sosial Angkatan Bersenjata Republik Indonesia (Persero)",
            "PT Bahana Pembinaan Usaha Indonesia (Persero)",
            "PT Reasuransi Indonesia Utama (Persero)",
            "PT Taspen (Persero)"
        ],
    "JASA_INFRASTRUKTUR":
        [
            "PT Adhi Karya (Persero) Tbk",
            "PT Brantas Abipraya (Persero)",
            "PT Hutama Karya (Persero)",
            "PT Jasa Marga (Persero) Tbk",
            "PT Pembangunan Perumahan (Persero) Tbk",
            "PT Semen Indonesia (Persero) Tbk",
            "PT Waskita Karya (Persero) Tbk",
            "PT Wijaya Karya (Persero) Tbk",
            "Perum Pembangunan Perumahan Nasional"
        ],
    "JASA_LOGISTIK":
        [
            "PT ASDP Indonesia Ferry (Persero)",
            "PT Kereta Api Indonesia (Persero)",
            "PT Pelabuhan Indonesia (Persero)",
            "PT Pelayaran Nasional Indonesia (Persero)",
            "PT Pos Indonesia (Persero)",
            "Perum DAMRI",
            "Perum Pengangkutan Penumpang Djakarta"
        ],
    "JASA_PARIWISATA_DAN_PENDUKUNG":
        [
            "PT Aviasi Pariwisata Indonesia (Persero)",
            "PT Garuda Indonesia (Persero) Tbk",
            "Perum Lembaga Penyelenggara Pelayanan Navigasi Penerbangan Indonesia"
        ],
    "SUBKLASTER_DANAREKSA":
        [
            "PT Virama Karya (Persero)",
            "PT Yodya Karya (Persero)",
            "PT Bina Karya (Persero)",
            "PT Indra Karya (Persero)",
            "Perum Jasa Tirta I",
            "Perum Jasa Tirta II",
            "PT Amarta Karya (Persero)",
            "PT Indah Karya (Persero)",
            "PT Barata Indonesia (Persero)",
            "PT Boma Bisma Indra (Persero)",
            "PT Djakarta Lloyd (Persero)",
            "PT Dok dan Perkapalan Kodja Bahari (Persero)",
            "PT Dok dan Perkapalan Surabaya (Persero)",
            "PT Industri Telekomunikasi Indonesia (Persero)",
            "PT Industri Kapal Indonesia (Persero)",
            "PT Pengusahaan Daerah Industri Pulau Batam (Persero)",
            "PT Primissima (Persero)",
            "PT Semen Kupang (Persero)",
            "PT Varuna Tirta Prakasya (Persero)",
            "Perum Lembaga Kantor Berita Nasional Antara",
            "Perum Percetakan Negara Republik Indonesia"
        ],
};