export const UPLOAD_DOCUMENTS =
    "TugasAkhirSPBE/App/UPLOAD_DOCUMENTS";
export const SUCCESS_UPLOAD_DOCUMENTS =
    "TugasAkhirSPBE/App/SUCCESS_UPLOAD_DOCUMENTS";
export const GET_INSTITUTION_DATA =
    "TugasAkhirSPBE/App/GET_INSTITUTION_DATA";
export const SET_INSTITUTION_DATA =
    "TugasAkhirSPBE/App/SET_INSTITUTION_DATA";